import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/source/styles/globals.scss";
import Header from '@/source/components/header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ua">
      <body className={inter.className}>
        <Header /> 
        {children}
        <footer>тут футер</footer>
      </body>
    </html>
  );
}
