import type { Metadata } from "next";
import "@/source/styles/globals.scss";
import Header from "@/source/components/header/header";
import Footer from "@/source/components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
}
